
[window]

opacity = 0.8

padding.x = 0
padding.y = 0

decorations = "Full"
decorations_theme_variant = "None" # "Dark"

[scrolling]

history = 10000

[font]

normal.family = "monospace"
size = 12.5

[colors]

draw_bold_text_with_bright_colors = true

[colors.primary]

foreground = "#cccccc"
background = "#000000"

[colors.normal]

black    = "#000000"
red      = "#aa0000"
green    = "#00aa00"
yellow   = "#aa5500"
blue     = "#3333aa"
magenta  = "#aa00aa"
cyan     = "#00aaaa"
white    = "#aaaaaa"

[colors.bright]

black    = "#555555"
red      = "#ff5555"
green    = "#55ff55"
yellow   = "#ffff55"
blue     = "#5555ff"
magenta  = "#ff55ff"
cyan     = "#55ffff"
white    = "#ffffff"

[[hints.enabled]]
command         = "xdg-open" # On Linux/BSD
hyperlinks      = true
post_processing = true
persist         = false
binding         = { key = "O", mods = "Control|Shift" }
regex ="(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩‘\\\\]+"
mouse = { mods = "Control", enabled = true }
